// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Adt
{
    public int Id { get; set; }

    public DateTime? EnteredDateTime { get; set; }

    public string? Transaction { get; set; }

    public string? WardLocation { get; set; }

    public string? RoomBed { get; set; }

    public string? Patient { get; set; }

    public int? PatientId { get; set; }

    public string? VisitId { get; set; }

    public string? AdmittingProvider { get; set; }

    public string? AttendingPhysician { get; set; }

    public string? Diagnosis { get; set; }

    public DateTime? AdmitDateTime { get; set; }

    public DateTime? DischargeDateTime { get; set; }

    public string? ChartNumber { get; set; }

    public string? WardAtDischarge { get; set; }

    public DateTime? LastModified { get; set; }

    public virtual Patient? PatientNavigation { get; set; }
}