// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class AlertDefRuleNode
{
    public int Id { get; set; }

    public int AlertDefId { get; set; }

    public int? ParentId { get; set; }

    public string? DataType { get; set; }

    public string? FieldName { get; set; }

    public string Operator { get; set; } = null!;

    public string? FieldDataType { get; set; }

    public string ChildOperator { get; set; } = null!;

    public string? Value { get; set; }

    public bool IsActive { get; set; }

    public virtual AlertDef AlertDef { get; set; } = null!;

    public virtual ICollection<AlertDefRuleNode> InverseParent { get; set; } = new List<AlertDefRuleNode>();

    public virtual AlertDefRuleNode? Parent { get; set; }
}