// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class AlertMessage
{
    public int Id { get; set; }

    public int AlertId { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Body { get; set; } = null!;

    public int? AuthUserId { get; set; }

    public virtual Alert Alert { get; set; } = null!;

    public virtual AuthUser? AuthUser { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();
}