// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class AlertDefCondition
{
    public int Id { get; set; }

    public int AlertDefId { get; set; }

    public int ConditionDefId { get; set; }

    public bool IsExclusion { get; set; }

    public int MinMatchCount { get; set; }

    public virtual AlertDef AlertDef { get; set; } = null!;

    public virtual ConditionDef ConditionDef { get; set; } = null!;
}