// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class AlertDef
{
    public int Id { get; set; }

    public string BaseName { get; set; } = null!;

    public string Origin { get; set; } = null!;

    public bool IsActive { get; set; }

    public string DisplayName { get; set; } = null!;

    public virtual ICollection<AlertDefCondition> AlertDefConditions { get; set; } = new List<AlertDefCondition>();

    public virtual ICollection<Alert> Alerts { get; set; } = new List<Alert>();
}