// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Alert
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Title { get; set; } = null!;

    public string? HtmlBody { get; set; }

    public int AlertDefId { get; set; }

    public int? AuthUserId { get; set; }

    public string Status { get; set; } = null!;

    public DateTime LastActivityAt { get; set; }

    public bool IsPrivate { get; set; }

    public virtual AlertDef AlertDef { get; set; } = null!;

    public virtual ICollection<AlertMessage> AlertMessages { get; set; } = new List<AlertMessage>();

    public virtual AuthUser? AuthUser { get; set; }
}