// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class AntibiogramOrganismGroup
{
    public string GroupName { get; set; } = null!;

    public virtual ICollection<AntibiogramOrganismMapping> AntibiogramOrganismMappings { get; set; } = new List<AntibiogramOrganismMapping>();
}