// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class AntibiogramOrganismMapping
{
    public string Organism { get; set; } = null!;

    public string AntibiogramOrganismGroupName { get; set; } = null!;

    public virtual AntibiogramOrganismGroup AntibiogramOrganismGroupNameNavigation { get; set; } = null!;
}