// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class AppSetting
{
    public string SettingName { get; set; } = null!;

    public string SettingValue { get; set; } = null!;
}