// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class BillingRx
{
    public int Id { get; set; }

    public DateTime? LastUpdate { get; set; }

    public DateTime? FillDate { get; set; }

    public string? RxNum { get; set; }

    public int? FillNum { get; set; }

    public double? Payable { get; set; }

    public string? PostedToAr { get; set; }

    public string? Rts { get; set; }

    public string? Paper { get; set; }

    public string? DrugId { get; set; }

    public string? Ndc { get; set; }

    public double? UnitPrice { get; set; }

    public double? Qty { get; set; }

    public double? TotalBilled { get; set; }

    public string? RejectionReasons { get; set; }

    public string? InsuranceName { get; set; }

    public string? InsuranceType { get; set; }

    public virtual HighCostQue? HighCostQue { get; set; }
}