// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class BlisterPackPatientActivity
{
    public long Id { get; set; }

    public int BlisterPackPatientId { get; set; }

    public string ActivityType { get; set; } = null!;

    public int? AuthUserId { get; set; }

    public DateTime ActivityAt { get; set; }

    public string Message { get; set; } = null!;

    public virtual AuthUser? AuthUser { get; set; }

    public virtual BlisterPackPatient BlisterPackPatient { get; set; } = null!;
}