// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class BlisterPackPatient
{
    public int PatientId { get; set; }

    public DateOnly EnrolledDate { get; set; }

    public DateOnly? DisenrollDate { get; set; }

    public bool Compliant { get; set; }

    public virtual ICollection<BlisterPackFill> BlisterPackFills { get; set; } = new List<BlisterPackFill>();

    public virtual ICollection<BlisterPackPatientActivity> BlisterPackPatientActivities { get; set; } = new List<BlisterPackPatientActivity>();

    public virtual Patient Patient { get; set; } = null!;
}