// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class BlisterPackFill
{
    public int Id { get; set; }

    public int BlisterPackPatientId { get; set; }

    public string? SerialNumbers { get; set; }

    public DateOnly FillDate { get; set; }

    public string Status { get; set; } = null!;

    public virtual ICollection<BlisterPackFillActivity> BlisterPackFillActivities { get; set; } = new List<BlisterPackFillActivity>();

    public virtual BlisterPackPatient BlisterPackPatient { get; set; } = null!;
}