// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class ClinicalDefinition
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string? Description { get; set; }

    public string DataType { get; set; } = null!;

    public bool IsActive { get; set; }

    public virtual ICollection<AlertDefRuleNode> AlertDefRuleNodes { get; set; } = new List<AlertDefRuleNode>();

    public virtual ICollection<ClinicalDefinitionItem> ClinicalDefinitionItems { get; set; } = new List<ClinicalDefinitionItem>();

    public virtual ICollection<ClinicalDefinitionMetadataMatch> ClinicalDefinitionMetadataMatches { get; set; } = new List<ClinicalDefinitionMetadataMatch>();
}