// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class ClinicalDefinitionItem
{
    public int Id { get; set; }

    public int ClinicalDefinitionId { get; set; }

    public string FieldName { get; set; } = null!;

    public string? Pattern { get; set; }

    public bool IsActive { get; set; }

    public virtual ClinicalDefinition ClinicalDefinition { get; set; } = null!;
}