// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class ClinicalDefinitionMetadataMatch
{
    public int Id { get; set; }

    public int ClinicalDefinitionId { get; set; }

    public string DataType { get; set; } = null!;

    public string MetadataRecordId { get; set; } = null!;

    public DateTime LastBuiltAt { get; set; }

    public virtual ClinicalDefinition ClinicalDefinition { get; set; } = null!;
}