// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class ConditionMatch
{
    public long Id { get; set; }

    public int ConditionDefId { get; set; }

    public int PatientId { get; set; }

    public string TableName { get; set; } = null!;

    public int SourceId { get; set; }

    public bool IsActive { get; set; }

    public DateTime MatchedAt { get; set; }

    public DateTime? EndedAt { get; set; }

    public virtual ConditionDef ConditionDef { get; set; } = null!;
}