// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class ConditionDef
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string ConditionType { get; set; } = null!;

    public string CriteriaJson { get; set; } = null!;

    public bool IsActive { get; set; }

    public virtual ICollection<AlertDefCondition> AlertDefConditions { get; set; } = new List<AlertDefCondition>();

    public virtual ICollection<ConditionMatch> ConditionMatches { get; set; } = new List<ConditionMatch>();
}