// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class DataGridTemplate
{
    public int Id { get; set; }

    public string TemplateName { get; set; } = null!;

    public string CreatedBy { get; set; } = null!;

    public bool IsShared { get; set; }

    public string DataGridName { get; set; } = null!;

    public string DataGridSettings { get; set; } = null!;
}