// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class DrugRequest
{
    public int Id { get; set; }

    public int? CreatedById { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? CompletedById { get; set; }

    public DateTime? CompletedAt { get; set; }

    public string? Ndc { get; set; }

    public double? PricePerOrder { get; set; }

    public double? OrderQty { get; set; }

    public int? DrugId { get; set; }

    public string? Comments { get; set; }

    public virtual AuthUser? CompletedBy { get; set; }

    public virtual AuthUser? CreatedBy { get; set; }

    public virtual Drug? Drug { get; set; }
}