// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class DrugRequestActivity
{
    public int Id { get; set; }

    public int? DrugRequestId { get; set; }

    public DateTime ActivityAt { get; set; }

    public int? AuthUserId { get; set; }

    public string? PreviousStatus { get; set; }

    public string NewStatus { get; set; } = null!;

    public virtual AuthUser? AuthUser { get; set; }

    public virtual DrugRequest? DrugRequest { get; set; }
}