// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Drug
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? PharmacyOrderableItem { get; set; }

    public string? DosageForm { get; set; }

    public string? DeaSpcl { get; set; }

    public string? OrderUnit { get; set; }

    public double? PricePerOrderUnit { get; set; }

    public double? BenchmarkPricePerDispenseUnit { get; set; }

    public string? DispenseUnit { get; set; }

    public double? DispenseUnitsPerOrderUnit { get; set; }

    public double? PricePerDispenseUnit { get; set; }

    public string? NcpdpDispenseUnit { get; set; }

    public string? VaPrintName { get; set; }

    public string? PackageSize { get; set; }

    public string? PackageType { get; set; }

    public string? DrugClass { get; set; }

    public string? Ndc { get; set; }

    public string? ApplicationPackage { get; set; }

    public string? Message { get; set; }

    public string? Restriction { get; set; }

    public string? Strength { get; set; }

    public string? Unit { get; set; }

    public string? PossibleDosages { get; set; }

    public string? LocalPossibleDosage { get; set; }

    public string? Synonym { get; set; }

    public string? Generic { get; set; }

    public DateTime? InactiveDate { get; set; }

    public string? PharmacyOrderableItemId { get; set; }

    public string? RxCui { get; set; }

    public string? Nf { get; set; }

    public virtual ICollection<WardstockItem> WardstockItems { get; set; } = new List<WardstockItem>();
}