// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class EmailNotificationRecipient
{
    public int Id { get; set; }

    public int? AuthUserId { get; set; }

    public int EmailNotificationConfigId { get; set; }

    public virtual AuthUser? AuthUser { get; set; }

    public virtual EmailNotificationConfig EmailNotificationConfig { get; set; } = null!;
}