// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class EmailNotificationConfig
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string SubjectPrefix { get; set; } = null!;

    public bool? IsEnabled { get; set; }

    public virtual ICollection<EmailNotificationRecipient> EmailNotificationRecipients { get; set; } = new List<EmailNotificationRecipient>();
}