// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class FilemanPrintTemplateItem
{
    public int Id { get; set; }

    public int? FilemanPrintTemplateId { get; set; }

    public string DataType { get; set; } = null!;

    public string Field { get; set; } = null!;

    public string? ColumnName { get; set; }

    public int SortOrder { get; set; }

    public virtual FilemanPrintTemplate? FilemanPrintTemplate { get; set; }
}