// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class FilemanPrintTemplate
{
    public int Id { get; set; }

    public string TemplateName { get; set; } = null!;

    public string? FileName { get; set; }

    public string? OptionName { get; set; }

    public string? TableName { get; set; }

    public virtual ICollection<FilemanPrintTemplateItem> FilemanPrintTemplateItems { get; set; } = new List<FilemanPrintTemplateItem>();
}