// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class GroupAutoMatch
{
    public int Id { get; set; }

    public string? AdGroup { get; set; }

    public int AuthGroupId { get; set; }

    public virtual AuthGroup AuthGroup { get; set; } = null!;
}