// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class HighCostQue
{
    public int Id { get; set; }

    public int? AuthUserId { get; set; }

    public DateTime? CompletedAt { get; set; }

    public virtual AuthUser? AuthUser { get; set; }

    public virtual BillingRx IdNavigation { get; set; } = null!;
}