// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class InpatientMedOrder
{
    public long? Id { get; set; }

    public string? ChartNumber { get; set; }

    public string? PatientId { get; set; }

    public string? PatientName { get; set; }

    public string? Provider { get; set; }

    public string? MedRoute { get; set; }

    public string OrderType { get; set; } = null!;

    public string? Remarks { get; set; }

    public string? Location { get; set; }

    public DateTime? AppointmentDateTime { get; set; }

    public DateTime? StartDateTime { get; set; }

    public DateTime? StopDateTime { get; set; }

    public string? VerifyingPharmacist { get; set; }

    public DateTime? VerifiedDateTime { get; set; }

    public string? Schedule { get; set; }

    public DateTime? LoginDateTime { get; set; }

    public string? ProviderComments { get; set; }

    public string? Instructions { get; set; }

    public string? OrderableItem { get; set; }

    public string? PharmacyOrderableItemId { get; set; }

    public string? DosageOrdered { get; set; }

    public string? DoseOrRate { get; set; }

    public bool Imo { get; set; }
}