// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Insurance
{
    public int Id { get; set; }

    public int PatientId { get; set; }

    public string? InsuranceCompany { get; set; }

    public string? InsuranceType { get; set; }

    public string? PolicyNumber { get; set; }

    public string? GroupName { get; set; }

    public DateOnly? EffectiveDate { get; set; }

    public DateOnly? ExpirationDate { get; set; }

    public virtual Patient Patient { get; set; } = null!;
}