// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Insurer
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Street { get; set; }

    public string? City { get; set; }

    public string? State { get; set; }

    public string? Zip { get; set; }

    public string? Phone { get; set; }

    public string? EinNumber { get; set; }

    public string? Status { get; set; }

    public string? TypeOfInsurer { get; set; }

    public string? InsurerType { get; set; }

    public string? AllInclusiveBilling { get; set; }

    public string? RxBillingStatus { get; set; }

    public string? DentalBillingStatus { get; set; }

    public virtual ICollection<Insurance> Insurances { get; set; } = new List<Insurance>();
}