// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Intervention
{
    public long Id { get; set; }

    public DateTime EntryDateTime { get; set; }

    public string? UserName { get; set; }

    public string? Comments { get; set; }

    public int? DrugId { get; set; }

    public int? ProviderId { get; set; }

    public string? ChartNumber { get; set; }

    public short? CategoryId { get; set; }

    public long LocationId { get; set; }

    public string LocationType { get; set; } = null!;

    public virtual InterventionCategory? Category { get; set; }

    public virtual InterventionLocation Location { get; set; } = null!;
}