// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class InterventionCategory
{
    public short Id { get; set; }

    public string? Name { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<Intervention> Interventions { get; set; } = new List<Intervention>();
}