// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Iv
{
    public long Id { get; set; }

    public string? PatientName { get; set; }

    public int? PatientId { get; set; }

    public DateTime? StartDateTime { get; set; }

    public DateTime? StopDateTime { get; set; }

    public string? Type { get; set; }

    public string? Provider { get; set; }

    public string? InfusionRate { get; set; }

    public string? Schedule { get; set; }

    public string? Remarks { get; set; }

    public string? AdministrationTimes { get; set; }

    public string? ScheduleInterval { get; set; }

    public DateTime? LoginDateTime { get; set; }

    public string? Additive { get; set; }

    public string? Solution { get; set; }

    public string? ActivityLog { get; set; }

    public string? Ward { get; set; }

    public string? Clinic { get; set; }

    public string? Status { get; set; }

    public string? ProviderComments { get; set; }

    public string? AutoDc { get; set; }

    public string? OrderableItem { get; set; }

    public int? PharmacyOrderableItemId { get; set; }

    public string? DosageOrdered { get; set; }

    public string? Instructions { get; set; }

    public DateTime? AppointmentDateTime { get; set; }

    public string? VerifyingPharmacist { get; set; }

    public DateTime? DateVerifiedByPharmacist { get; set; }

    public string? BcmaId { get; set; }

    public virtual Patient? Patient { get; set; }

    public virtual PharmacyOrderableItem? PharmacyOrderableItem { get; set; }
}