// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class IvcompoundingLog
{
    public DateOnly DateCompounded { get; set; }

    public int CompoundedQty { get; set; }
}