// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Lab
{
    public int Id { get; set; }

    public int PatientId { get; set; }

    public DateTime? VisitDateTime { get; set; }

    public string? VisitId { get; set; }

    public string? LabTest { get; set; }

    public string? Results { get; set; }

    public string? Units { get; set; }

    public string? RangeLow { get; set; }

    public string? RangeHigh { get; set; }

    public string? Order { get; set; }

    public string? Specimen { get; set; }

    public string? IcdCode { get; set; }

    public string? CollectionSample { get; set; }

    public DateTime? CollectionDateAndTime { get; set; }

    public DateTime? ResultDateAndTime { get; set; }

    public DateTime? OrderingDate { get; set; }

    public string? Clinic { get; set; }

    public string? OrderingLocation { get; set; }

    public virtual Patient Patient { get; set; } = null!;
}