// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class LeaveRequestActivity
{
    public long Id { get; set; }

    public int? LeaveRequestId { get; set; }

    public string ActivityType { get; set; } = null!;

    public string? ChangedField { get; set; }

    public int AuthUserId { get; set; }

    public DateTime ActivityAt { get; set; }

    public string Message { get; set; } = null!;

    public virtual AuthUser AuthUser { get; set; } = null!;

    public virtual LeaveRequest? LeaveRequest { get; set; }
}