// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class LeaveRequest
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateOnly LeaveStart { get; set; }

    public DateOnly LeaveEnd { get; set; }

    public int RequestedById { get; set; }

    public string Status { get; set; } = null!;

    public string LeaveType { get; set; } = null!;

    public DateTime LastModifiedAt { get; set; }

    public virtual ICollection<LeaveRequestActivity> LeaveRequestActivities { get; set; } = new List<LeaveRequestActivity>();

    public virtual AuthUser RequestedBy { get; set; } = null!;
}