// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class LookupValue
{
    public int Id { get; set; }

    public string OptionSet { get; set; } = null!;

    public string Value { get; set; } = null!;

    public string? DisplayText { get; set; }

    public int SortOrder { get; set; }

    public bool IsActive { get; set; }

    public string? Options { get; set; }
}