// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AutoCAC.Models;

public partial class mainContext : DbContext
{
    public mainContext(DbContextOptions<mainContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Adt> Adts { get; set; }

    public virtual DbSet<AuthGroup> AuthGroups { get; set; }

    public virtual DbSet<AuthUser> AuthUsers { get; set; }

    public virtual DbSet<AuthUserGroup> AuthUserGroups { get; set; }

    public virtual DbSet<DataGridTemplate> DataGridTemplates { get; set; }

    public virtual DbSet<Drug> Drugs { get; set; }

    public virtual DbSet<GroupAutoMatch> GroupAutoMatches { get; set; }

    public virtual DbSet<InpatientMedOrder> InpatientMedOrders { get; set; }

    public virtual DbSet<MenuBuild> MenuBuilds { get; set; }

    public virtual DbSet<MenuBuildMetum> MenuBuildMeta { get; set; }

    public virtual DbSet<Ndf> Ndfs { get; set; }

    public virtual DbSet<NightShiftRotation> NightShiftRotations { get; set; }

    public virtual DbSet<NurseCompoundTraining> NurseCompoundTrainings { get; set; }

    public virtual DbSet<OrderDialog> OrderDialogs { get; set; }

    public virtual DbSet<OrderMenu> OrderMenus { get; set; }

    public virtual DbSet<Patient> Patients { get; set; }

    public virtual DbSet<PatientLink> PatientLinks { get; set; }

    public virtual DbSet<PharmacyOrderableItem> PharmacyOrderableItems { get; set; }

    public virtual DbSet<PiVerification> PiVerifications { get; set; }

    public virtual DbSet<PiVerificationComment> PiVerificationComments { get; set; }

    public virtual DbSet<RestrictedPage> RestrictedPages { get; set; }

    public virtual DbSet<RestrictedPageGroup> RestrictedPageGroups { get; set; }

    public virtual DbSet<Tiu> Tius { get; set; }

    public virtual DbSet<TsaileActivitylog> TsaileActivitylogs { get; set; }

    public virtual DbSet<TsaileBetterq> TsaileBetterqs { get; set; }

    public virtual DbSet<TsaileComment> TsaileComments { get; set; }

    public virtual DbSet<TsailePatient> TsailePatients { get; set; }

    public virtual DbSet<VwNdcLookup> VwNdcLookups { get; set; }

    public virtual DbSet<VwUserNameMismatch> VwUserNameMismatches { get; set; }

    public virtual DbSet<VwVancomycinAuc> VwVancomycinAucs { get; set; }

    public virtual DbSet<WardstockActivitylog> WardstockActivitylogs { get; set; }

    public virtual DbSet<WardstockComment> WardstockComments { get; set; }

    public virtual DbSet<WardstockItem> WardstockItems { get; set; }

    public virtual DbSet<WardstockLocation> WardstockLocations { get; set; }

    public virtual DbSet<WardstockOrder> WardstockOrders { get; set; }

    public virtual DbSet<WardstockOrderitem> WardstockOrderitems { get; set; }

    public virtual DbSet<WardstockUserlocation> WardstockUserlocations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Adt>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ADT__3213E83FDBE06C19");

            entity.ToTable("ADT");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.AdmitDateTime).HasColumnType("datetime");
            entity.Property(e => e.AdmittingProvider).IsUnicode(false);
            entity.Property(e => e.AttendingPhysician).IsUnicode(false);
            entity.Property(e => e.ChartNumber).IsUnicode(false);
            entity.Property(e => e.Diagnosis).IsUnicode(false);
            entity.Property(e => e.DischargeDateTime).HasColumnType("datetime");
            entity.Property(e => e.EnteredDateTime).HasColumnType("datetime");
            entity.Property(e => e.LastModified).HasColumnType("datetime");
            entity.Property(e => e.Patient).IsUnicode(false);
            entity.Property(e => e.PatientId).HasColumnName("PatientID");
            entity.Property(e => e.RoomBed).IsUnicode(false);
            entity.Property(e => e.Transaction).IsUnicode(false);
            entity.Property(e => e.VisitId)
                .IsUnicode(false)
                .HasColumnName("VisitID");
            entity.Property(e => e.WardAtDischarge).IsUnicode(false);
            entity.Property(e => e.WardLocation).IsUnicode(false);

            entity.HasOne(d => d.PatientNavigation).WithMany(p => p.Adts)
                .HasForeignKey(d => d.PatientId)
                .HasConstraintName("FK_ADT_PatientId");
        });

        modelBuilder.Entity<AuthGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__auth_gro__3213E83FC1044636");

            entity.ToTable("auth_group");

            entity.HasIndex(e => e.Name, "auth_group_name_a6ea08ec_uniq").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .HasMaxLength(150)
                .HasColumnName("name");
        });

        modelBuilder.Entity<AuthUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__auth_use__3213E83F5DF4B627");

            entity.ToTable("auth_user");

            entity.HasIndex(e => e.Username, "auth_user_username_6821ab7c_uniq").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.DateJoined).HasColumnName("date_joined");
            entity.Property(e => e.Email)
                .HasMaxLength(254)
                .HasColumnName("email");
            entity.Property(e => e.FirstName)
                .HasMaxLength(150)
                .HasColumnName("first_name");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.IsStaff).HasColumnName("is_staff");
            entity.Property(e => e.IsSuperuser).HasColumnName("is_superuser");
            entity.Property(e => e.LastLogin).HasColumnName("last_login");
            entity.Property(e => e.LastName)
                .HasMaxLength(150)
                .HasColumnName("last_name");
            entity.Property(e => e.Password)
                .HasMaxLength(128)
                .HasColumnName("password");
            entity.Property(e => e.Username)
                .HasMaxLength(150)
                .HasColumnName("username");
        });

        modelBuilder.Entity<AuthUserGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__auth_use__3213E83FFFAA0339");

            entity.ToTable("auth_user_groups");

            entity.HasIndex(e => e.GroupId, "auth_user_groups_group_id_97559544");

            entity.HasIndex(e => e.UserId, "auth_user_groups_user_id_6a12ed8b");

            entity.HasIndex(e => new { e.UserId, e.GroupId }, "auth_user_groups_user_id_group_id_94350c0c_uniq")
                .IsUnique()
                .HasFilter("([user_id] IS NOT NULL AND [group_id] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Group).WithMany(p => p.AuthUserGroups)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("auth_user_groups_group_id_97559544_fk_auth_group_id");

            entity.HasOne(d => d.User).WithMany(p => p.AuthUserGroups)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("auth_user_groups_user_id_6a12ed8b_fk_auth_user_id");
        });

        modelBuilder.Entity<DataGridTemplate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DataGrid__3214EC072ACDA0C4");

            entity.HasIndex(e => new { e.CreatedBy, e.DataGridName }, "IX_DataGridTemplates_CreatedBy");

            entity.HasIndex(e => new { e.CreatedBy, e.DataGridName, e.TemplateName }, "UX_DataGridTemplates_User_Grid_Name").IsUnique();

            entity.Property(e => e.CreatedBy).HasMaxLength(225);
            entity.Property(e => e.DataGridName).HasMaxLength(225);
            entity.Property(e => e.TemplateName).HasMaxLength(225);
        });

        modelBuilder.Entity<Drug>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Drug__3213E83F85628773");

            entity.ToTable("Drug");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.ApplicationPackage).IsUnicode(false);
            entity.Property(e => e.DeaSpcl).IsUnicode(false);
            entity.Property(e => e.DispenseUnit).IsUnicode(false);
            entity.Property(e => e.DosageForm).IsUnicode(false);
            entity.Property(e => e.DrugClass).IsUnicode(false);
            entity.Property(e => e.Generic).IsUnicode(false);
            entity.Property(e => e.InactiveDate).HasColumnType("datetime");
            entity.Property(e => e.LocalPossibleDosage).IsUnicode(false);
            entity.Property(e => e.Message).IsUnicode(false);
            entity.Property(e => e.Name).IsUnicode(false);
            entity.Property(e => e.NcpdpDispenseUnit).IsUnicode(false);
            entity.Property(e => e.Ndc).IsUnicode(false);
            entity.Property(e => e.Nf)
                .IsUnicode(false)
                .HasColumnName("NF");
            entity.Property(e => e.OrderUnit).IsUnicode(false);
            entity.Property(e => e.PackageSize).IsUnicode(false);
            entity.Property(e => e.PackageType).IsUnicode(false);
            entity.Property(e => e.PharmacyOrderableItem).IsUnicode(false);
            entity.Property(e => e.PharmacyOrderableItemId)
                .IsUnicode(false)
                .HasColumnName("PharmacyOrderableItemID");
            entity.Property(e => e.PossibleDosages).IsUnicode(false);
            entity.Property(e => e.Restriction).IsUnicode(false);
            entity.Property(e => e.RxCui)
                .IsUnicode(false)
                .HasColumnName("RxCUI");
            entity.Property(e => e.Strength).IsUnicode(false);
            entity.Property(e => e.Synonym).IsUnicode(false);
            entity.Property(e => e.Unit).IsUnicode(false);
            entity.Property(e => e.VaPrintName).IsUnicode(false);
        });

        modelBuilder.Entity<GroupAutoMatch>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__GroupAut__3213E83F3D06E5A8");

            entity.ToTable("GroupAutoMatch");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AdGroup).HasMaxLength(150);
            entity.Property(e => e.AuthGroupId).HasColumnName("auth_group_id");

            entity.HasOne(d => d.AuthGroup).WithMany(p => p.GroupAutoMatches)
                .HasForeignKey(d => d.AuthGroupId)
                .HasConstraintName("FK_GroupAutoMatch_auth_group");
        });

        modelBuilder.Entity<InpatientMedOrder>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("InpatientMedOrder");

            entity.Property(e => e.AppointmentDateTime).HasColumnType("datetime");
            entity.Property(e => e.ChartNumber).IsUnicode(false);
            entity.Property(e => e.DosageOrdered).IsUnicode(false);
            entity.Property(e => e.DoseOrRate).IsUnicode(false);
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Imo).HasColumnName("IMO");
            entity.Property(e => e.Instructions).IsUnicode(false);
            entity.Property(e => e.Location).IsUnicode(false);
            entity.Property(e => e.LoginDateTime).HasColumnType("datetime");
            entity.Property(e => e.MedRoute).IsUnicode(false);
            entity.Property(e => e.OrderType)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.OrderableItem).IsUnicode(false);
            entity.Property(e => e.PatientId)
                .IsUnicode(false)
                .HasColumnName("PatientID");
            entity.Property(e => e.PatientName).IsUnicode(false);
            entity.Property(e => e.PharmacyOrderableItemId)
                .IsUnicode(false)
                .HasColumnName("PharmacyOrderableItemID");
            entity.Property(e => e.Provider).IsUnicode(false);
            entity.Property(e => e.ProviderComments).IsUnicode(false);
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.Schedule).IsUnicode(false);
            entity.Property(e => e.StartDateTime).HasColumnType("datetime");
            entity.Property(e => e.StopDateTime).HasColumnType("datetime");
            entity.Property(e => e.VerifiedDateTime).HasColumnType("datetime");
            entity.Property(e => e.VerifyingPharmacist).IsUnicode(false);
        });

        modelBuilder.Entity<MenuBuild>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MenuBuil__3214EC07338C1A0A");

            entity.ToTable("MenuBuild");

            entity.HasIndex(e => new { e.MenuId, e.RowNum, e.ColNum }, "UQ_MenuBuild_MenuRowCol").IsUnique();

            entity.Property(e => e.AdditionalDetails).HasMaxLength(255);
            entity.Property(e => e.DisplayOnly).HasMaxLength(50);
            entity.Property(e => e.DisplayText).HasMaxLength(255);
            entity.Property(e => e.ItemId).HasColumnName("Item_id");
            entity.Property(e => e.MenuId).HasColumnName("Menu_id");
            entity.Property(e => e.Mnemonic).HasMaxLength(4);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();

            entity.HasOne(d => d.Item).WithMany(p => p.MenuBuilds)
                .HasForeignKey(d => d.ItemId)
                .HasConstraintName("FK_MenuBuildItem_OrderDialog");

            entity.HasOne(d => d.Menu).WithMany(p => p.MenuBuilds)
                .HasForeignKey(d => d.MenuId)
                .HasConstraintName("FK_MenuBuild_MenuBuildMeta");
        });

        modelBuilder.Entity<MenuBuildMetum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MenuBuil__3213E83F297792AB");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Columns).HasDefaultValue((byte)3);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.DisplayText).IsUnicode(false);
            entity.Property(e => e.Name).IsUnicode(false);
            entity.Property(e => e.RequestStatus)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasDefaultValue("NEW", "DEFAULT_MenuBuildMeta_RequestStatus");
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();

            entity.HasOne(d => d.ExistingMenuNavigation).WithMany(p => p.MenuBuildMeta)
                .HasForeignKey(d => d.ExistingMenu)
                .HasConstraintName("FK_MenuBuildMeta_ExistingMenu");
        });

        modelBuilder.Entity<Ndf>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__NDF__3213E83F3D09905B");

            entity.ToTable("NDF");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Dea).IsUnicode(false);
            entity.Property(e => e.DispenseUnit).IsUnicode(false);
            entity.Property(e => e.Generic).IsUnicode(false);
            entity.Property(e => e.InactiveDate).HasColumnType("datetime");
            entity.Property(e => e.Ndc)
                .IsUnicode(false)
                .HasColumnName("NDC");
            entity.Property(e => e.PackageSize).IsUnicode(false);
            entity.Property(e => e.PackageType).IsUnicode(false);
            entity.Property(e => e.PrintName).IsUnicode(false);
            entity.Property(e => e.ProductName).IsUnicode(false);
        });

        modelBuilder.Entity<NightShiftRotation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__NightShi__3214EC07E8BD3384");

            entity.ToTable("NightShiftRotation");

            entity.Property(e => e.StaffUserName)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<NurseCompoundTraining>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__NurseCom__3214EC07DEC1F7E8");

            entity.ToTable("NurseCompoundTraining");

            entity.Property(e => e.Department)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.StaffUserName).HasMaxLength(150);

            entity.HasOne(d => d.StaffUserNameNavigation).WithMany(p => p.NurseCompoundTrainings)
                .HasPrincipalKey(p => p.Username)
                .HasForeignKey(d => d.StaffUserName)
                .HasConstraintName("FK_NurseCompundTraining_StaffUserName");
        });

        modelBuilder.Entity<OrderDialog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderDia__3213E83F092BEE58");

            entity.ToTable("OrderDialog");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.DisplayGroup).IsUnicode(false);
            entity.Property(e => e.DisplayText).IsUnicode(false);
            entity.Property(e => e.Items).IsUnicode(false);
            entity.Property(e => e.Name).IsUnicode(false);
            entity.Property(e => e.Package).IsUnicode(false);
            entity.Property(e => e.Responses).IsUnicode(false);
            entity.Property(e => e.Type).IsUnicode(false);
        });

        modelBuilder.Entity<OrderMenu>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("OrderMenu");

            entity.Property(e => e.DisplayOnly).HasMaxLength(4000);
            entity.Property(e => e.DisplayText).HasMaxLength(4000);
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Item).HasMaxLength(4000);
            entity.Property(e => e.ItemDisplay).IsUnicode(false);
            entity.Property(e => e.Mnemonic).HasMaxLength(4000);
            entity.Property(e => e.OrderDialogId)
                .HasMaxLength(4000)
                .HasColumnName("OrderDialogID");
            entity.Property(e => e.Seq).HasMaxLength(4000);
        });

        modelBuilder.Entity<Patient>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Patient__3213E83F57C79012");

            entity.ToTable("Patient");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Age).IsUnicode(false);
            entity.Property(e => e.AttendingPhysician).IsUnicode(false);
            entity.Property(e => e.CellNumber).IsUnicode(false);
            entity.Property(e => e.ChartNumber).IsUnicode(false);
            entity.Property(e => e.CurrentAdmission).HasColumnType("datetime");
            entity.Property(e => e.CurrentMovement).HasColumnType("datetime");
            entity.Property(e => e.DateEnteredIntoFile).IsUnicode(false);
            entity.Property(e => e.DateOfDeath).HasColumnType("datetime");
            entity.Property(e => e.Diagnosis).IsUnicode(false);
            entity.Property(e => e.Dob)
                .HasColumnType("datetime")
                .HasColumnName("DOB");
            entity.Property(e => e.HomePhone).IsUnicode(false);
            entity.Property(e => e.Last4).IsUnicode(false);
            entity.Property(e => e.Name).IsUnicode(false);
            entity.Property(e => e.Pcp)
                .IsUnicode(false)
                .HasColumnName("PCP");
            entity.Property(e => e.Race).IsUnicode(false);
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.RoomBed).IsUnicode(false);
            entity.Property(e => e.Sex).IsUnicode(false);
            entity.Property(e => e.Veteran).IsUnicode(false);
            entity.Property(e => e.WardLocation).IsUnicode(false);
            entity.Property(e => e.WorkPhone).IsUnicode(false);
            entity.Property(e => e.ZipCode).IsUnicode(false);
        });

        modelBuilder.Entity<PatientLink>(entity =>
        {
            entity.HasKey(e => e.LinkId).HasName("PK__PatientL__2D12215575D04739");

            entity.ToTable("PatientLink");

            entity.Property(e => e.LinkId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("LinkID");
            entity.Property(e => e.PatientId).HasColumnName("PatientID");

            entity.HasOne(d => d.Patient).WithMany(p => p.PatientLinks)
                .HasForeignKey(d => d.PatientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PatientLink_PatientID");
        });

        modelBuilder.Entity<PharmacyOrderableItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Pharmacy__3213E83F86EA7B67");

            entity.ToTable("PharmacyOrderableItem");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.AlertMsg).IsUnicode(false);
            entity.Property(e => e.AssociatedImmunization).IsUnicode(false);
            entity.Property(e => e.DayOrDoseLimit).IsUnicode(false);
            entity.Property(e => e.DefaultMedRoute).IsUnicode(false);
            entity.Property(e => e.DosageForm).IsUnicode(false);
            entity.Property(e => e.FormularyStatus).IsUnicode(false);
            entity.Property(e => e.InactiveDate).IsUnicode(false);
            entity.Property(e => e.IvFlag).IsUnicode(false);
            entity.Property(e => e.MedRoutes).IsUnicode(false);
            entity.Property(e => e.OrderableName).IsUnicode(false);
            entity.Property(e => e.PatientInstructions).IsUnicode(false);
            entity.Property(e => e.Schedule).IsUnicode(false);
            entity.Property(e => e.ScheduleType).IsUnicode(false);
            entity.Property(e => e.Synonym).IsUnicode(false);
        });

        modelBuilder.Entity<PiVerification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PI_Verif__3213E83FC31227B3");

            entity.ToTable("PI_Verification");

            entity.HasIndex(e => e.PatientId, "PI_Verification_patient_id_idx");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Bin).HasMaxLength(10);
            entity.Property(e => e.CardholderId)
                .HasMaxLength(100)
                .HasColumnName("CardholderID");
            entity.Property(e => e.CompletedBy).HasMaxLength(255);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())", "DF_PI_Verification_CreatedAt");
            entity.Property(e => e.CreatedBy).HasMaxLength(255);
            entity.Property(e => e.CurrentStatus)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasDefaultValue("NEW");
            entity.Property(e => e.GroupId)
                .HasMaxLength(100)
                .HasColumnName("GroupID");
            entity.Property(e => e.PatientId).HasColumnName("patient_id");
            entity.Property(e => e.Pcn).HasMaxLength(50);
            entity.Property(e => e.SubmittedBy).HasMaxLength(255);
            entity.Property(e => e.VerifiedBy).HasMaxLength(255);

            entity.HasOne(d => d.Patient).WithMany(p => p.PiVerifications)
                .HasForeignKey(d => d.PatientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PI_Verification_patient_id");
        });

        modelBuilder.Entity<PiVerificationComment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PI_Verif__3213E83FB70B60E0");

            entity.ToTable("PI_VerificationComment");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Comment).IsUnicode(false);
            entity.Property(e => e.CommentStep)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.PiVerificationId).HasColumnName("PI_Verification_id");

            entity.HasOne(d => d.PiVerification).WithMany(p => p.PiVerificationComments)
                .HasForeignKey(d => d.PiVerificationId)
                .HasConstraintName("FK_PI_VerificationComment_PI_Verification");
        });

        modelBuilder.Entity<RestrictedPage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Restrict__3214EC077DAF73BB");

            entity.ToTable("RestrictedPage");

            entity.HasIndex(e => e.RelativeUrl, "UQ_RestrictedPage_RelativeUrl").IsUnique();

            entity.Property(e => e.AlwaysAllowSuperusers).HasDefaultValue(true);
            entity.Property(e => e.RelativeUrl)
                .HasMaxLength(200)
                .IsUnicode(false);
        });

        modelBuilder.Entity<RestrictedPageGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Restrict__3214EC075D0D9584");

            entity.ToTable("RestrictedPageGroup");

            entity.Property(e => e.AuthGroupId).HasColumnName("auth_group_id");
            entity.Property(e => e.RestrictedPageId).HasColumnName("RestrictedPage_id");

            entity.HasOne(d => d.AuthGroup).WithMany(p => p.RestrictedPageGroups)
                .HasForeignKey(d => d.AuthGroupId)
                .HasConstraintName("FK_RestrictedPageGroup_auth_group");

            entity.HasOne(d => d.RestrictedPage).WithMany(p => p.RestrictedPageGroups)
                .HasForeignKey(d => d.RestrictedPageId)
                .HasConstraintName("FK_RestrictedPageGroup_RestrictedPage");
        });

        modelBuilder.Entity<Tiu>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TIU__3213E83F134EACEB");

            entity.ToTable("TIU");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Author).IsUnicode(false);
            entity.Property(e => e.Division).IsUnicode(false);
            entity.Property(e => e.DocumentType).IsUnicode(false);
            entity.Property(e => e.EntryDateTime).HasColumnType("datetime");
            entity.Property(e => e.HospitalLocation).IsUnicode(false);
            entity.Property(e => e.PatientId).HasColumnName("PatientID");
            entity.Property(e => e.StaffId)
                .IsUnicode(false)
                .HasColumnName("StaffID");
            entity.Property(e => e.VisitDateTime).HasColumnType("datetime");
            entity.Property(e => e.VisitId)
                .IsUnicode(false)
                .HasColumnName("VisitID");

            entity.HasOne(d => d.Patient).WithMany(p => p.Tius)
                .HasForeignKey(d => d.PatientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Tiu_Patient");
        });

        modelBuilder.Entity<TsaileActivitylog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tsaile_a__3213E83F292954BB");

            entity.ToTable("tsaile_activitylog");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AuthUserId).HasColumnName("auth_user_id");
            entity.Property(e => e.ChangedFrom)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.ChangedTo)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.TsaileBetterqId).HasColumnName("tsaile_betterq_id");

            entity.HasOne(d => d.AuthUser).WithMany(p => p.TsaileActivitylogs)
                .HasForeignKey(d => d.AuthUserId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_tsaile_activitylog_auth_user");

            entity.HasOne(d => d.TsaileBetterq).WithMany(p => p.TsaileActivitylogs)
                .HasForeignKey(d => d.TsaileBetterqId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_tsaile_activitylog_tsaile_betterq");
        });

        modelBuilder.Entity<TsaileBetterq>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tsaile_b__3213E83FA30F7FBB");

            entity.ToTable("tsaile_betterq");

            entity.HasIndex(e => new { e.Status, e.Waiting, e.LastModifiedDateTime }, "IX_tsaile_betterq_ActiveQueue").HasFilter("([CompletedDateTime] IS NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Efdt).HasColumnName("EFDT");
            entity.Property(e => e.NeedsCounseling).HasDefaultValue(true);
            entity.Property(e => e.Status).HasMaxLength(100);

            entity.HasOne(d => d.Patient).WithMany(p => p.TsaileBetterqs)
                .HasForeignKey(d => d.PatientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tsaile_betterq_PatientId");
        });

        modelBuilder.Entity<TsaileComment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tsaile_c__3213E83FEBE15C21");

            entity.ToTable("tsaile_comment");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AuthUserId).HasColumnName("auth_user_id");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Remarks)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.TsaileBetterqId).HasColumnName("tsaile_betterq_id");

            entity.HasOne(d => d.AuthUser).WithMany(p => p.TsaileComments)
                .HasForeignKey(d => d.AuthUserId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_tsaile_comment_auth_user");

            entity.HasOne(d => d.TsaileBetterq).WithMany(p => p.TsaileComments)
                .HasForeignKey(d => d.TsaileBetterqId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_tsaile_comment_tsaile_betterq");
        });

        modelBuilder.Entity<TsailePatient>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TsailePa__3213E83F55FAA269");

            entity.ToTable("TsailePatient");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Age).IsUnicode(false);
            entity.Property(e => e.AttendingPhysician).IsUnicode(false);
            entity.Property(e => e.CellNumber).IsUnicode(false);
            entity.Property(e => e.ChartNumber).IsUnicode(false);
            entity.Property(e => e.CurrentAdmission).HasColumnType("datetime");
            entity.Property(e => e.CurrentMovement).HasColumnType("datetime");
            entity.Property(e => e.DateEnteredIntoFile).IsUnicode(false);
            entity.Property(e => e.DateOfDeath).HasColumnType("datetime");
            entity.Property(e => e.Diagnosis).IsUnicode(false);
            entity.Property(e => e.Dob)
                .HasColumnType("datetime")
                .HasColumnName("DOB");
            entity.Property(e => e.HomePhone).IsUnicode(false);
            entity.Property(e => e.Last4).IsUnicode(false);
            entity.Property(e => e.Name).IsUnicode(false);
            entity.Property(e => e.Pcp)
                .IsUnicode(false)
                .HasColumnName("PCP");
            entity.Property(e => e.Race).IsUnicode(false);
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.RoomBed).IsUnicode(false);
            entity.Property(e => e.Sex).IsUnicode(false);
            entity.Property(e => e.Veteran).IsUnicode(false);
            entity.Property(e => e.WardLocation).IsUnicode(false);
            entity.Property(e => e.WorkPhone).IsUnicode(false);
            entity.Property(e => e.ZipCode).IsUnicode(false);
        });

        modelBuilder.Entity<VwNdcLookup>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_NdcLookup");

            entity.Property(e => e.CurrentIen).HasColumnName("CurrentIEN");
            entity.Property(e => e.CurrentNdc)
                .IsUnicode(false)
                .HasColumnName("CurrentNDC");
            entity.Property(e => e.Dea).IsUnicode(false);
            entity.Property(e => e.DispenseUnit).IsUnicode(false);
            entity.Property(e => e.DrugFileName).IsUnicode(false);
            entity.Property(e => e.Generic).IsUnicode(false);
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.InactiveDate).HasColumnType("datetime");
            entity.Property(e => e.Ndc)
                .IsUnicode(false)
                .HasColumnName("NDC");
            entity.Property(e => e.NdfInactiveDate).HasColumnType("datetime");
            entity.Property(e => e.PackageSize).IsUnicode(false);
            entity.Property(e => e.PackageType).IsUnicode(false);
            entity.Property(e => e.PrintName).IsUnicode(false);
            entity.Property(e => e.ProductName).IsUnicode(false);
        });

        modelBuilder.Entity<VwUserNameMismatch>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_UserNameMismatch");

            entity.Property(e => e.AppFirstName).HasMaxLength(150);
            entity.Property(e => e.AppLastName).HasMaxLength(150);
            entity.Property(e => e.RpmsfirstName)
                .IsUnicode(false)
                .HasColumnName("RPMSFirstName");
            entity.Property(e => e.RpmslastName)
                .IsUnicode(false)
                .HasColumnName("RPMSLastName");
            entity.Property(e => e.Username)
                .HasMaxLength(150)
                .HasColumnName("username");
        });

        modelBuilder.Entity<VwVancomycinAuc>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_VancomycinAuc");

            entity.Property(e => e.Auc).HasColumnName("AUC");
            entity.Property(e => e.DispenseDrug).IsUnicode(false);
            entity.Property(e => e.GivenAt).HasColumnType("datetime");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Peak).HasColumnType("decimal(6, 1)");
            entity.Property(e => e.T1).HasColumnType("decimal(9, 1)");
            entity.Property(e => e.T2).HasColumnType("decimal(9, 1)");
            entity.Property(e => e.Tinf).HasColumnType("decimal(9, 1)");
            entity.Property(e => e.Trough).HasColumnType("decimal(6, 1)");
            entity.Property(e => e.TruePeak).HasColumnType("decimal(9, 1)");
            entity.Property(e => e.TrueTrough).HasColumnType("decimal(9, 1)");
        });

        modelBuilder.Entity<WardstockActivitylog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__wardstoc__3213E83FE8FC59EF");

            entity.ToTable("wardstock_activitylog");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ActivityAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.AuthUserId).HasColumnName("auth_user_id");
            entity.Property(e => e.Remarks).HasMaxLength(255);
            entity.Property(e => e.WardstockOrderId).HasColumnName("wardstock_order_id");

            entity.HasOne(d => d.AuthUser).WithMany(p => p.WardstockActivitylogs)
                .HasForeignKey(d => d.AuthUserId)
                .HasConstraintName("FK_wardstock_activitylog_auth_user");

            entity.HasOne(d => d.WardstockOrder).WithMany(p => p.WardstockActivitylogs)
                .HasForeignKey(d => d.WardstockOrderId)
                .HasConstraintName("fk_wardstock_activitylog_wardstock_order_id");
        });

        modelBuilder.Entity<WardstockComment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__wardstoc__3214EC07B35F1EB0");

            entity.ToTable("wardstock_comment");

            entity.Property(e => e.AuthUserId).HasColumnName("auth_user_id");
            entity.Property(e => e.Comment).IsUnicode(false);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(4)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.WardstockOrderId).HasColumnName("wardstock_order_id");

            entity.HasOne(d => d.AuthUser).WithMany(p => p.WardstockComments)
                .HasForeignKey(d => d.AuthUserId)
                .HasConstraintName("FK_wardstock_comment_auth_user");

            entity.HasOne(d => d.WardstockOrder).WithMany(p => p.WardstockComments)
                .HasForeignKey(d => d.WardstockOrderId)
                .HasConstraintName("FK_wardstock_comment_wardstock_order");
        });

        modelBuilder.Entity<WardstockItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_wardstock_item");

            entity.ToTable("wardstock_item");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Category)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.DisplayName).HasMaxLength(255);
            entity.Property(e => e.DrugId).HasColumnName("Drug_id");
            entity.Property(e => e.LocationId).HasColumnName("Location_id");

            entity.HasOne(d => d.Drug).WithMany(p => p.WardstockItems)
                .HasForeignKey(d => d.DrugId)
                .HasConstraintName("FK_wardstock_item_Drug_id");

            entity.HasOne(d => d.Location).WithMany(p => p.WardstockItems)
                .HasForeignKey(d => d.LocationId)
                .HasConstraintName("FK_wardstock_item_Location_id");
        });

        modelBuilder.Entity<WardstockLocation>(entity =>
        {
            entity.ToTable("wardstock_location");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.LocationName).HasMaxLength(255);
        });

        modelBuilder.Entity<WardstockOrder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__wardstoc__3213E83F71E2302B");

            entity.ToTable("wardstock_order");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.LocationId).HasColumnName("Location_id");
            entity.Property(e => e.Status).HasMaxLength(20);

            entity.HasOne(d => d.Location).WithMany(p => p.WardstockOrders)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_wardstock_order_wardstock_Location_id");
        });

        modelBuilder.Entity<WardstockOrderitem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__wardstoc__3213E83F2CEEBC5D");

            entity.ToTable("wardstock_orderitem");

            entity.HasIndex(e => e.OrderId, "wardstock_orderitem_Order_id_151c8c0d");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ItemId).HasColumnName("Item_id");
            entity.Property(e => e.Lot).HasMaxLength(255);
            entity.Property(e => e.OrderId).HasColumnName("Order_id");

            entity.HasOne(d => d.Item).WithMany(p => p.WardstockOrderitems)
                .HasForeignKey(d => d.ItemId)
                .HasConstraintName("FK_wardstock_orderitem_Item_id");

            entity.HasOne(d => d.Order).WithMany(p => p.WardstockOrderitems)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_wardstock_orderitem_order_id");
        });

        modelBuilder.Entity<WardstockUserlocation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__wardstoc__3213E83F303F25D9");

            entity.ToTable("wardstock_userlocation");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AuthUserId).HasColumnName("auth_user_id");
            entity.Property(e => e.LocationId).HasColumnName("Location_id");

            entity.HasOne(d => d.AuthUser).WithMany(p => p.WardstockUserlocations)
                .HasForeignKey(d => d.AuthUserId)
                .HasConstraintName("FK_wardstock_userlocation_auth_user_id");

            entity.HasOne(d => d.Location).WithMany(p => p.WardstockUserlocations)
                .HasForeignKey(d => d.LocationId)
                .HasConstraintName("wardstock_userlocation_wardstock_location_id");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}