// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class MenuBuildMetum
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string DisplayText { get; set; } = null!;

    public byte Columns { get; set; }

    public string RequestStatus { get; set; } = null!;

    public int? ExistingMenu { get; set; }

    public byte[] RowVersion { get; set; } = null!;

    public virtual OrderDialog? ExistingMenuNavigation { get; set; }

    public virtual ICollection<MenuBuild> MenuBuilds { get; set; } = new List<MenuBuild>();
}