// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class MenuItemChange
{
    public int? MenuId { get; set; }

    public int? RowNum { get; set; }

    public int? ColNum { get; set; }

    public string? ChangeType { get; set; }

    public int? NewItemId { get; set; }

    public string? NewMnemonic { get; set; }

    public string? NewDisplayText { get; set; }

    public string? NewDisplayOnly { get; set; }

    public string? NewItemDisplay { get; set; }

    public string? OldItemId { get; set; }

    public string? OldMnemonic { get; set; }

    public string? OldDisplayText { get; set; }

    public string? OldDisplayOnly { get; set; }

    public string? OldItemDisplay { get; set; }
}