// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class MenuBuild
{
    public int Id { get; set; }

    public int MenuId { get; set; }

    public int? ItemId { get; set; }

    public string? Mnemonic { get; set; }

    public string? DisplayText { get; set; }

    public string? DisplayOnly { get; set; }

    public int RowNum { get; set; }

    public int ColNum { get; set; }

    public byte[] RowVersion { get; set; } = null!;

    public virtual OrderDialog? Item { get; set; }

    public virtual MenuBuildMetum Menu { get; set; } = null!;
}