// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Microbio
{
    public int Id { get; set; }

    public int? PatientId { get; set; }

    public DateTime? VisitDateTime { get; set; }

    public long? VisitId { get; set; }

    public string? Organism { get; set; }

    public string? Antibiotic { get; set; }

    public string? Culture { get; set; }

    public string? Result { get; set; }

    public DateTime? CompleteDate { get; set; }

    public DateTime? LastModified { get; set; }

    public string? IcdCode { get; set; }

    public DateTime? DateTimeEntered { get; set; }

    public DateTime? CollectionDateTime { get; set; }

    public string? AccessionNumber { get; set; }

    public string? GramStain { get; set; }

    public virtual Patient? Patient { get; set; }
}