// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Notification
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? LastSeenAt { get; set; }

    public DateTime LastModifiedAt { get; set; }

    public int AuthUserId { get; set; }

    public int AlertId { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool HasUnseenActivity { get; set; }

    public virtual Alert Alert { get; set; } = null!;

    public virtual AuthUser AuthUser { get; set; } = null!;
}