// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Notification
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ReadAt { get; set; }

    public int AuthUserId { get; set; }

    public int AlertMessageId { get; set; }

    public virtual AlertMessage AlertMessage { get; set; } = null!;

    public virtual AuthUser AuthUser { get; set; } = null!;
}