// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class NurseCompoundTraining
{
    public int Id { get; set; }

    public string StaffUserName { get; set; } = null!;

    public string? Department { get; set; }

    public DateOnly? DateLiveTraining { get; set; }

    public DateOnly? DateAsepticTechnique { get; set; }

    public DateOnly? DateCompetencyQuiz { get; set; }

    public DateOnly? DateRenewalDue { get; set; }
}