// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class OrderMenu
{
    public int Id { get; set; }

    public string? Seq { get; set; }

    public string? OrderDialogId { get; set; }

    public string? Item { get; set; }

    public string? Mnemonic { get; set; }

    public string? DisplayText { get; set; }

    public string? DisplayOnly { get; set; }

    public string? ItemDisplay { get; set; }

    public int? RowNum { get; set; }

    public int? ColNum { get; set; }
}