// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class OrderDialogResponse
{
    public int ParentOrderDialogId { get; set; }

    public int ItemEntry { get; set; }

    public int Instance { get; set; }

    public string? Value { get; set; }

    public virtual OrderDialog ParentOrderDialog { get; set; } = null!;
}