// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class PatientLink
{
    public Guid LinkId { get; set; }

    public int PatientId { get; set; }

    public virtual Patient Patient { get; set; } = null!;
}