// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Patient
{
    public int Id { get; set; }

    public string? ChartNumber { get; set; }

    public string? Name { get; set; }

    public string? Sex { get; set; }

    public DateTime? Dob { get; set; }

    public int? Age { get; set; }

    public string? Race { get; set; }

    public string? Pcp { get; set; }

    public string? Remarks { get; set; }

    public string? DateEnteredIntoFile { get; set; }

    public string? WardLocation { get; set; }

    public string? RoomBed { get; set; }

    public DateTime? CurrentMovement { get; set; }

    public string? Diagnosis { get; set; }

    public string? AttendingPhysician { get; set; }

    public DateTime? CurrentAdmission { get; set; }

    public DateTime? DateOfDeath { get; set; }

    public string? Veteran { get; set; }

    public string? CellNumber { get; set; }

    public string? HomePhone { get; set; }

    public string? WorkPhone { get; set; }

    public string? ZipCode { get; set; }

    public string? Last4 { get; set; }

    public string? State { get; set; }

    public string? TsaileChartNumber { get; set; }

    public string? PinonChartNumber { get; set; }

    public string? ChartList { get; set; }

    public virtual ICollection<Adt> Adts { get; set; } = new List<Adt>();

    public virtual ICollection<Insurance> Insurances { get; set; } = new List<Insurance>();

    public virtual ICollection<Lab> Labs { get; set; } = new List<Lab>();

    public virtual ICollection<Microbio> Microbios { get; set; } = new List<Microbio>();

    public virtual ICollection<PiVerification> PiVerifications { get; set; } = new List<PiVerification>();

    public virtual ICollection<RxFill> RxFills { get; set; } = new List<RxFill>();

    public virtual ICollection<Rx> Rxes { get; set; } = new List<Rx>();

    public virtual ICollection<Tiu> Tius { get; set; } = new List<Tiu>();

    public virtual ICollection<TsaileBetterq> TsaileBetterqs { get; set; } = new List<TsaileBetterq>();

    public virtual ICollection<TsailePatientcomment> TsailePatientcomments { get; set; } = new List<TsailePatientcomment>();

    public virtual ICollection<Visit> Visits { get; set; } = new List<Visit>();

    public virtual ICollection<Vital> Vitals { get; set; } = new List<Vital>();
}