// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class PharmacyOrderableItem
{
    public int Id { get; set; }

    public string? OrderableName { get; set; }

    public string? DosageForm { get; set; }

    public string? IvFlag { get; set; }

    public string? InactiveDate { get; set; }

    public string? DayOrDoseLimit { get; set; }

    public string? DefaultMedRoute { get; set; }

    public string? ScheduleType { get; set; }

    public string? Schedule { get; set; }

    public string? Synonym { get; set; }

    public string? FormularyStatus { get; set; }

    public string? AlertMsg { get; set; }

    public string? PatientInstructions { get; set; }

    public string? AssociatedImmunization { get; set; }

    public string? MedRoutes { get; set; }
}