// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class PiVerification
{
    public int Id { get; set; }

    public string? Bin { get; set; }

    public string? Pcn { get; set; }

    public string? GroupId { get; set; }

    public string? CardholderId { get; set; }

    public string? CreatedBy { get; set; }

    public string? SubmittedBy { get; set; }

    public string? VerifiedBy { get; set; }

    public string? CompletedBy { get; set; }

    public DateTime LastModified { get; set; }

    public DateTime CreatedAt { get; set; }

    public string? PharmacyRemarks { get; set; }

    public int PatientId { get; set; }

    public string? VerifierRemarks { get; set; }

    public string CurrentStatus { get; set; } = null!;

    public virtual Patient Patient { get; set; } = null!;

    public virtual ICollection<PiVerificationComment> PiVerificationComments { get; set; } = new List<PiVerificationComment>();
}