// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class PiVerificationComment
{
    public int Id { get; set; }

    public int PiVerificationId { get; set; }

    public string CommentStep { get; set; } = null!;

    public string Comment { get; set; } = null!;

    public string CreatedBy { get; set; } = null!;

    public DateTime CreatedAt { get; set; }

    public virtual PiVerification PiVerification { get; set; } = null!;
}