// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class QuickOrder
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? DisplayText { get; set; }

    public string? DisplayGroup { get; set; }

    public string? Package { get; set; }

    public string? Responses { get; set; }
}