// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class QuickOrderContent
{
    public int Id { get; set; }

    public int? ItemEntry { get; set; }

    public string? EntryType { get; set; }

    public int? Instance { get; set; }

    public string? Value { get; set; }

    public string? Qoname { get; set; }

    public string? QodisplayName { get; set; }

    public string? QodisplayGroup { get; set; }
}