// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class RejectCode
{
    public string Code { get; set; } = null!;

    public string? Preventable { get; set; }

    public string? Explanation { get; set; }

    public string? Category { get; set; }
}