// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class RestrictedPage
{
    public int Id { get; set; }

    public string RelativeUrl { get; set; } = null!;

    public bool ApplyToChildUrls { get; set; }

    public bool AlwaysAllowSuperusers { get; set; }

    public virtual ICollection<RestrictedPageGroup> RestrictedPageGroups { get; set; } = new List<RestrictedPageGroup>();
}