// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class RestrictedPageGroup
{
    public int Id { get; set; }

    public int RestrictedPageId { get; set; }

    public int AuthGroupId { get; set; }

    public virtual AuthGroup AuthGroup { get; set; } = null!;

    public virtual RestrictedPage RestrictedPage { get; set; } = null!;
}