// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class RpmsactivityLog
{
    public int Id { get; set; }

    public int? AuthUserId { get; set; }

    public DateTime ActivityAt { get; set; }

    public string ActivityDescription { get; set; } = null!;

    public virtual AuthUser? AuthUser { get; set; }
}