// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class RuleEngineSourceState
{
    public string TableName { get; set; } = null!;

    public DateTime LastImportAt { get; set; }

    public DateTime? LastProcessedAt { get; set; }

    public DateTime? ProcessingStartedAt { get; set; }
}