// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class RuleEngineFact
{
    public long Id { get; set; }

    public string DataType { get; set; } = null!;

    public string? TableName { get; set; }

    public int? PatientId { get; set; }

    public string RecordKey { get; set; } = null!;

    public int Instance { get; set; }

    public string FieldName { get; set; } = null!;

    public string? FieldValue { get; set; }

    public bool IsActive { get; set; }

    public DateTime LastImportAt { get; set; }

    public bool NeedsProcessing { get; set; }
}