// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Rx
{
    public int Id { get; set; }

    public string? Rx1 { get; set; }

    public DateTime? IssueDate { get; set; }

    public string? Patient { get; set; }

    public int PatientId { get; set; }

    public string? Provider { get; set; }

    public string? Clinic { get; set; }

    public string? Drug { get; set; }

    public string? DrugId { get; set; }

    public string? Qty { get; set; }

    public string? DaysSupply { get; set; }

    public string? OrigNumRefills { get; set; }

    public string? Remarks { get; set; }

    public string? EnteredBy { get; set; }

    public string? UnitPriceOfDrug { get; set; }

    public string? Division { get; set; }

    public string? Pharmacist { get; set; }

    public DateTime? ExpirationDate { get; set; }

    public DateTime? CancelDate { get; set; }

    public string? Ndc { get; set; }

    public string? CsHardcopy { get; set; }

    public string? Manufacturer { get; set; }

    public DateTime? ReleasedDateTime { get; set; }

    public string? FinishingPerson { get; set; }

    public string? PharmacyOrderableItemId { get; set; }

    public DateTime? HoldDate { get; set; }

    public string? Status { get; set; }

    public string? PatientInstructions { get; set; }

    public string? Instructions { get; set; }

    public string? SignOrSymptom { get; set; }

    public string? IndicationCode { get; set; }

    public string? Sig { get; set; }

    public string? Refill { get; set; }

    public string? Insurance { get; set; }

    public string? Rts { get; set; }

    public DateTime? LastModified { get; set; }

    public virtual Patient PatientNavigation { get; set; } = null!;

    public virtual ICollection<RxFill> RxFills { get; set; } = new List<RxFill>();
}