// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class RxFill
{
    public int RxId { get; set; }

    public int FillNum { get; set; }

    public int PatientId { get; set; }

    public DateTime? ReleasedDateTime { get; set; }

    public decimal? Qty { get; set; }

    public decimal? UnitPrice { get; set; }

    public string? Rts { get; set; }

    public int DrugId { get; set; }

    public virtual Patient Patient { get; set; } = null!;

    public virtual Rx Rx { get; set; } = null!;
}