// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class ScheduledTaskSchedule
{
    public int Id { get; set; }

    public int ScheduledTaskId { get; set; }

    public string ScheduleType { get; set; } = null!;

    public TimeOnly TimeOfDay { get; set; }

    public byte? DayOfWeek { get; set; }

    public byte? DayOfMonth { get; set; }

    public DateTime LastModifiedAt { get; set; }

    public virtual ScheduledTask ScheduledTask { get; set; } = null!;
}