// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class ScheduledTask
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string HandlerKey { get; set; } = null!;

    public string? ParametersJson { get; set; }

    public DateTime? LastRunAt { get; set; }

    public DateTime? NextRunAt { get; set; }

    public DateTime LastModifiedAt { get; set; }

    public virtual ICollection<ScheduledTaskSchedule> ScheduledTaskSchedules { get; set; } = new List<ScheduledTaskSchedule>();
}