// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Staff
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? EmailAddress { get; set; }

    public string? Initial { get; set; }

    public string? Sex { get; set; }

    public string? Dob { get; set; }

    public string? Disuser { get; set; }

    public string? Title { get; set; }

    public DateTime? TerminationDate { get; set; }

    public string? Division { get; set; }

    public string? Keys { get; set; }

    public string? AuthorizedToWriteMedOrders { get; set; }

    public string? VaNum { get; set; }

    public string? Dea { get; set; }

    public DateTime? InactiveDate { get; set; }

    public string? ProviderClass { get; set; }

    public string? ProviderType { get; set; }

    public string? PrimaryMenuOption { get; set; }

    public string? SecondaryMenuOptions { get; set; }

    public string? PositionTitle { get; set; }

    public string? ServiceSection { get; set; }
}