// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Tiu
{
    public int Id { get; set; }

    public string? DocumentType { get; set; }

    public int PatientId { get; set; }

    public string? VisitId { get; set; }

    public DateTime? VisitDateTime { get; set; }

    public DateTime? EntryDateTime { get; set; }

    public string? Author { get; set; }

    public string? StaffId { get; set; }

    public string? HospitalLocation { get; set; }

    public string? Division { get; set; }

    public virtual Patient Patient { get; set; } = null!;
}