// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class TsailePatientcomment
{
    public long Id { get; set; }

    public int? PatientId { get; set; }

    public int? AuthUserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Comment { get; set; } = null!;

    public virtual AuthUser? AuthUser { get; set; }

    public virtual TsailePatient? Patient { get; set; }
}