// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class TsaileBetterq
{
    public long Id { get; set; }

    public DateTime CreatedDateTime { get; set; }

    public DateTime? CompletedDateTime { get; set; }

    public string Status { get; set; } = null!;

    public bool Waiting { get; set; }

    public DateTime? LockedDateTime { get; set; }

    public DateTime LastModifiedDateTime { get; set; }

    public DateTime? CalledDateTime { get; set; }

    public bool ControlledSubstance { get; set; }

    public DateOnly? Efdt { get; set; }

    public int PatientId { get; set; }

    public string BatchTo { get; set; } = null!;

    public int? LockedById { get; set; }

    public virtual AuthUser? LockedBy { get; set; }

    public virtual TsailePatient Patient { get; set; } = null!;

    public virtual ICollection<TsaileActivitylog> TsaileActivitylogs { get; set; } = new List<TsaileActivitylog>();

    public virtual ICollection<TsaileComment> TsaileComments { get; set; } = new List<TsaileComment>();
}