// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class TsaileComment
{
    public int Id { get; set; }

    public long? TsaileBetterqId { get; set; }

    public int? AuthUserId { get; set; }

    public string Remarks { get; set; } = null!;

    public DateTime CreatedAt { get; set; }

    public virtual AuthUser? AuthUser { get; set; }

    public virtual TsaileBetterq? TsaileBetterq { get; set; }
}