// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class TsaileActivitylog
{
    public long Id { get; set; }

    public string? ChangedFrom { get; set; }

    public string ChangedTo { get; set; } = null!;

    public long? TsaileBetterqId { get; set; }

    public int? AuthUserId { get; set; }

    public DateTime ChangedAt { get; set; }

    public virtual AuthUser? AuthUser { get; set; }

    public virtual TsaileBetterq? TsaileBetterq { get; set; }
}