// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Ud
{
    public int Id { get; set; }

    public string? PatientName { get; set; }

    public string? PatientId { get; set; }

    public string? Provider { get; set; }

    public string? MedRoute { get; set; }

    public string? Type { get; set; }

    public string? ScheduleType { get; set; }

    public string? SpecialInstructions { get; set; }

    public string? Clinic { get; set; }

    public string? Ward { get; set; }

    public DateTime? AppointmentDateTime { get; set; }

    public DateTime? StartDateTime { get; set; }

    public DateTime? StopDateTime { get; set; }

    public string? DayLimit { get; set; }

    public string? DoseLimit { get; set; }

    public string? VerifyingPharmacist { get; set; }

    public DateTime? VerifiedDateTime { get; set; }

    public string? Physician { get; set; }

    public string? Clerk { get; set; }

    public string? Schedule { get; set; }

    public DateTime? LogInDate { get; set; }

    public DateTime? OrderDate { get; set; }

    public string? Status { get; set; }

    public string? AdminTimes { get; set; }

    public string? ProviderComments { get; set; }

    public string? Instructions { get; set; }

    public int? PharmacyOrderableItemId { get; set; }

    public string? OrderableItem { get; set; }

    public string? DosageOrdered { get; set; }

    public string? ActivityLog { get; set; }

    public string? DispenseDrug { get; set; }

    public string? Dose { get; set; }

    public virtual PharmacyOrderableItem? PharmacyOrderableItem { get; set; }
}