// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Visit
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? HospitalLocation { get; set; }

    public string? LocationId { get; set; }

    public int? PatientId { get; set; }

    public DateTime? CheckOutDateTime { get; set; }

    public string? ServiceCategory { get; set; }

    public string? Billed { get; set; }

    public DateTime? VisitAdmitDateTime { get; set; }

    public virtual Patient? Patient { get; set; }
}