// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class Vital
{
    public int Id { get; set; }

    public int PatientId { get; set; }

    public DateTime? VisitDateTime { get; set; }

    public string? VisitId { get; set; }

    public string? Type { get; set; }

    public double Value { get; set; }

    public DateTime? EventDateTime { get; set; }

    public DateTime? DateTimeLastModified { get; set; }

    public virtual Patient Patient { get; set; } = null!;
}