// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class VwBillingRx
{
    public int Id { get; set; }

    public DateTime? LastUpdate { get; set; }

    public DateTime? FillDate { get; set; }

    public string? RxNum { get; set; }

    public int? FillNum { get; set; }

    public double? TotalBilled { get; set; }

    public double? TotalPaid { get; set; }

    public string? Paper { get; set; }

    public string? DrugId { get; set; }

    public string? DrugName { get; set; }

    public string? Ndc { get; set; }

    public double? UnitPrice { get; set; }

    public double? Qty { get; set; }

    public string? RejectionReasons { get; set; }

    public string? InsuranceName { get; set; }

    public string? InsuranceType { get; set; }

    public int PatientId { get; set; }

    public string? PatientName { get; set; }

    public string? ChartNumber { get; set; }

    public DateTime? Dob { get; set; }

    public int RxId { get; set; }
}