// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class VwNdcLookup
{
    public int Id { get; set; }

    public string? Ndc { get; set; }

    public string? ProductName { get; set; }

    public string? Generic { get; set; }

    public string? PrintName { get; set; }

    public string? DispenseUnit { get; set; }

    public string? Dea { get; set; }

    public DateTime? NdfInactiveDate { get; set; }

    public string? PackageType { get; set; }

    public string? PackageSize { get; set; }

    public int? CurrentIen { get; set; }

    public string? DrugFileName { get; set; }

    public string? CurrentNdc { get; set; }

    public DateTime? InactiveDate { get; set; }
}