// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class VwUserNameMismatch
{
    public string Username { get; set; } = null!;

    public string? RpmslastName { get; set; }

    public string? AppLastName { get; set; }

    public string? RpmsfirstName { get; set; }

    public string? AppFirstName { get; set; }

    public int? PossibleMatches { get; set; }
}