// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class VwVancomycinAuc
{
    public int Id { get; set; }

    public int? Auc { get; set; }

    public decimal? TruePeak { get; set; }

    public decimal? TrueTrough { get; set; }

    public decimal? Peak { get; set; }

    public decimal? Trough { get; set; }

    public int? Tau { get; set; }

    public decimal? Tinf { get; set; }

    public decimal? T1 { get; set; }

    public decimal? T2 { get; set; }

    public string? DispenseDrug { get; set; }

    public DateTime? GivenAt { get; set; }
}