// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class WardstockActivitylog
{
    public int Id { get; set; }

    public int? AuthUserId { get; set; }

    public DateTime ActivityAt { get; set; }

    public string Remarks { get; set; } = null!;

    public long WardstockOrderId { get; set; }

    public virtual AuthUser? AuthUser { get; set; }

    public virtual WardstockOrder WardstockOrder { get; set; } = null!;
}