// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class WardstockOrder
{
    public long Id { get; set; }

    public DateTime? OrderDateTime { get; set; }

    public DateTime? LastModifiedDateTime { get; set; }

    public int LocationId { get; set; }

    public string Status { get; set; } = null!;

    public string? Comments { get; set; }

    public virtual WardstockLocation Location { get; set; } = null!;

    public virtual ICollection<WardstockActivitylog> WardstockActivitylogs { get; set; } = new List<WardstockActivitylog>();

    public virtual ICollection<WardstockComment> WardstockComments { get; set; } = new List<WardstockComment>();

    public virtual ICollection<WardstockOrderitem> WardstockOrderitems { get; set; } = new List<WardstockOrderitem>();
}