// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class WardstockOrderitem
{
    public long Id { get; set; }

    public int ItemId { get; set; }

    public long OrderId { get; set; }

    public string? Lot { get; set; }

    public double? QtyFilled { get; set; }

    public double? QtyOrdered { get; set; }

    public string? Comments { get; set; }

    public virtual WardstockItem Item { get; set; } = null!;

    public virtual WardstockOrder Order { get; set; } = null!;
}