// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class WardstockItem
{
    public int Id { get; set; }

    public int? DrugId { get; set; }

    public int LocationId { get; set; }

    public double Par { get; set; }

    public string DisplayName { get; set; } = null!;

    public string Category { get; set; } = null!;

    public virtual Drug? Drug { get; set; }

    public virtual WardstockLocation Location { get; set; } = null!;

    public virtual ICollection<WardstockOrderitem> WardstockOrderitems { get; set; } = new List<WardstockOrderitem>();
}