// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class WardstockLocation
{
    public int Id { get; set; }

    public string LocationName { get; set; } = null!;

    public DateOnly? InactiveDate { get; set; }

    public virtual ICollection<WardstockItem> WardstockItems { get; set; } = new List<WardstockItem>();

    public virtual ICollection<WardstockOrder> WardstockOrders { get; set; } = new List<WardstockOrder>();

    public virtual ICollection<WardstockUserlocation> WardstockUserlocations { get; set; } = new List<WardstockUserlocation>();
}