// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class WardstockComment
{
    public long Id { get; set; }

    public long WardstockOrderId { get; set; }

    public int AuthUserId { get; set; }

    public string Comment { get; set; } = null!;

    public DateTime CreatedAt { get; set; }

    public virtual AuthUser AuthUser { get; set; } = null!;

    public virtual WardstockOrder WardstockOrder { get; set; } = null!;
}