// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AutoCAC.Models;

public partial class WardstockUserlocation
{
    public long Id { get; set; }

    public int LocationId { get; set; }

    public int AuthUserId { get; set; }

    public virtual AuthUser AuthUser { get; set; } = null!;

    public virtual WardstockLocation Location { get; set; } = null!;
}